#!/usr/bin/env python

import json
from subprocess import Popen, PIPE
import difflib

tick = '\xE2\x9C\x94'
cross = '\xE2\x9C\x97'
pass_colour = '\033[92m'
fail_colour = '\033[91m'
end_colour = '\033[0m'

tests = json.loads(open('tests.json').read())['cases']

i = 1
num_tests = len(tests)

for test in tests:
    input_ = '\n'.join(test['input'])
    expected_output = '\n'.join(test['output'])

    process = Popen(['phonebook'], stdin=PIPE, stdout=PIPE)
    output, error = process.communicate(input=input_)

    didPass = output == expected_output
    colour = pass_colour if didPass else fail_colour
    symbol = tick if didPass else cross
    word = 'passed' if didPass else 'failed'

    print '%sTest %d of %d %s %s%s' % (colour, i, num_tests, word, symbol, end_colour)
    print 'The program should %s.' % test['it_should']

    if not didPass:
        differ = difflib.Differ()
        diff = difflib.ndiff(output.splitlines(), expected_output.splitlines())
        print '\n'.join(diff)

    i += 1
